---
title: Wat is JSON?
hero_image: images/banner.png
description: Wat is JSON?
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "gegevens"
technologies: "json"
steps:
  - 
    title: JSON
