---
title: Was ist JSON?
hero_image: images/banner.png
description: Was ist JSON?
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: "Daten"
technologies: "json"
steps:
  - title: JSON
