---
title: Ce este JSON?
hero_image: images/banner.png
description: Ce este JSON?
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "data"
technologies: "json"
steps:
  - 
    title: JSON
