---
title: ما المقصود بـ JSON؟
hero_image: images/banner.png
description: ما المقصود بـ JSON؟
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: "data"
technologies: "json"
steps:
  - 
    title: JSON
