---
title: JSON은 무엇입니까?
hero_image: images/banner.png
description: JSON은 무엇입니까?
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "데이터"
technologies: "json"
steps:
  - 
    title: JSON
