---
title: Čo je JSON?
hero_image: images/banner.png
description: Čo je JSON?
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "dáta"
technologies: "json"
steps:
  - 
    title: JSON
